services:
  - type: web
    name: tradesaathi
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SMARTAPI_API_KEY
        sync: false
      - key: SMARTAPI_CLIENT_CODE
        sync: false
      - key: SMARTAPI_MPIN
        sync: false
      - key: SMARTAPI_TOTP_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
